
INSERT INTO piloto (nombre, apellido, numero, nacionalidad) VALUES
('Max', 'Verstappen', 1, 'Países Bajos'),
('Lando', 'Norris', 4, 'Reino Unido'),
('Charles', 'Leclerc', 16, 'Mónaco'),
('Oscar', 'Piastri', 81, 'Australia'),
('Carlos', 'Sainz', 55, 'España'),
('George', 'Russell', 63, 'Reino Unido'),
('Lewis', 'Hamilton', 44, 'Reino Unido'),
('Sergio', 'Pérez', 11, 'México'),
('Fernando', 'Alonso', 14, 'España'),
('Pierre', 'Gasly', 10, 'Francia'),
('Nico', 'Hulkenberg', 27, 'Alemania'),
('Yuki', 'Tsunoda', 22, 'Japón'),
('Lance', 'Stroll', 18, 'Canadá'),
('Esteban', 'Ocon', 31, 'Francia'),
('Kevin', 'Magnussen', 20, 'Dinamarca'),
('Alexander', 'Albon', 23, 'Tailandia'),
('Daniel', 'Ricciardo', 3, 'Australia'),
('Oliver', 'Bearman', 38, 'Reino Unido'),
('Franco', 'Colapinto', 43, 'Argentina'),
('Zhou', 'Guanyu', 24, 'China'),
('Liam', 'Lawson', 30, 'Nueva Zelanda'),
('Valtteri', 'Bottas', 77, 'Finlandia'),
('Logan', 'Sargeant', 2, 'EE.UU.'),
('Jack', 'Doohan', 40, 'Australia'),
('Kimi', 'Antonelli', 7, 'Italia'),
('Isack', 'Hadjar', 50, 'Francia'),
('Gabriel', 'Bortoleto', 51, 'Brasil');
